# Generated by Django 4.2.29 on 2026-03-08 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', '送信前'), ('sending', '送信中'), ('success', '送信成功'), ('failed', '送信失敗')], max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dementia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.dementia')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordingSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_symptom', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordings.recording')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_condition', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.condition')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordings.recording')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recordingsymptom',
            constraint=models.UniqueConstraint(fields=('recording', 'symptom'), name='unique_recording_symptom'),
        ),
        migrations.AddConstraint(
            model_name='recordingcondition',
            constraint=models.UniqueConstraint(fields=('recording', 'condition'), name='unique_recording_condition'),
        ),
    ]
