# Generated by Django 4.2.29 on 2026-03-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('patient_code', models.CharField(max_length=100)),
                ('biological_sex', models.CharField(choices=[('man', '男性'), ('woman', '女性'), ('other', 'その他')], max_length=10)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
            ],
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('patient_code', 'facility'), name='unique_patient_code_per_facility'),
        ),
    ]
